
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/MerchantFront
      username: root
      password: Syam123$@

  jpa:
      show-sql: true
      hibernate:
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL5Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 923941412683-9jrfv9mjblutbpevd7b103loig8lej29.apps.googleusercontent.com
            clientSecret: 7pOVfKUeNOkyApdi8x0PAAoe
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - https://pipertravel.com/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
  api:
     host: http://localhost:8080
     ui: http://localhost:3000
  payment:
     merchantId: 0cd33757-7e7c-11ea-834e-0a423e8ef63e
     signKey: 646x0rfZ
     secret: mer123
     host: https://api.oacquiring.com
     terminal:
       USD: cfc56101-5528-11ea-834e-0a423e8ef63e
       EUR: cfc56101-5528-11ea-834e-0a423e8ef63e
       NGN: cfc56101-5528-11ea-834e-0a423e8ef63e

server:
  port: 8080